#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 17 17:45:27 2020

@author: rajkumarshrivastava
"""
import sys
def gcd(a, b):
    if b==0:
        return a
    return gcd(b, a%b)

if __name__ == '__main__':
    data = sys.stdin.read().split('\n')
    N = int(data[0])
    radius = list(map(int, data[1].split()))
    
    for i in range(1, N):
        div = gcd(radius[0], radius[i])
        print("{}/{}".format(radius[0]//div, radius[i]//div))
        #print(radius[0]//div,'/',radius[i]//div, delimiter = '')
