#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 17 18:22:52 2020

@author: rajkumarshrivastava
"""

import sys
def gcd(a, b):
    if b==0:
        return a
    return gcd(b, a%b)

if __name__ == '__main__':
    data = sys.stdin.read().split('/')
    nr, dr = list(map(int,data))
    nr = 5*(nr - 32*dr)
    dr = 9*dr
    div = gcd(nr, dr)
    print("{}/{}".format(nr//div, dr//div))
